[package]
name = "ministatus"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
toml = { version = "1", default-features = false, features = ["std", "parse", "serde"] }
jiff = { version = "0.2", default-features = false, features = ["std", "tz-system", "tzdb-zoneinfo"] }
anyhow = "1"
x11 = { version = "2.21", default-features = false, features = ["xlib"] }

# news
rusqlite = "0.40"

# weather
ureq = { version = "3.0.0", default-features = false, features = ["rustls", "json"] }
serde = { version = "1.0.202", features = ["derive"] }

# pulse
libpulse-binding = "2"

[profile.release]
lto = true
codegen-units = 1
strip = true

[lints.rust]
warnings = "deny"

[lints.clippy]
nursery = { level = "allow", priority = -1 }

pedantic = "deny"

all = "deny"
correctness = "deny"
suspicious = "deny"
perf = "deny"
complexity = "deny"

unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
indexing_slicing = "deny"
await_holding_lock = "deny"

needless_borrow = "deny"
needless_collect = "deny"
large_stack_arrays = "deny"
